version: 2.1

docker_defaults: &docker_defaults
  context: dockerhub
  image: oneflare/$CIRCLE_PROJECT_REPONAME

orbs:
  docker: circleci/docker@2.0.5

workflows:
  version: 2
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          <<: *docker_defaults
          tag: ${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:7},${CIRCLE_BRANCH}
      - docker/publish:
          <<: *docker_defaults
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          tag: ${CIRCLE_TAG}
